column_renaming = {
    "DATE": "date",
    "CD_CVM": "cdCvm",
    "VALUE": "value",
    "TICKER": "ticker",
    "MAIN_TICKER": "ticker",
    "TICKERS": "tickers",
    "NAME": "name",
    "SEGMENT": "segment",
    "MARKET_CAP": "marketCap",
    "PRICE": "price",
    "BAZIN": "bazinPrice",
    "PRICE_PROFIT": "priceProfit",
    "PRICE_EQUITY": "priceEquity",
    "DIVIDEND_YIELD": "dividendYield",
    "DIVIDEND_PAYOUT": "dividendPayout",
    "EQUITY": "equity",
    "NET_REVENUE": "netRevenue",
    "PROFIT": "profit",
    "EBIT": "ebit",
    "DEBT": "debt",
    "DEBT_NET": "netDebt",
    "NET_MARGIN": "netMargin",
    "ROE": "roe",
    "NET_DEBT_BY_EBIT": "netDebtByEbit",
    "NET_DEBT_BY_EQUITY": "netDebtByEquity",
    "CAGR_5_YEARS_PROFIT": "cagr5YearsProfit",
    "CAGR_5_YEARS_REVENUE": "cagr5YearsRevenue",
}

kpi_by_group = {
    "value": ["PRICE_PROFIT", "PRICE_EQUITY", "DIVIDEND_YIELD", "DIVIDEND_PAYOUT"],
    "debt": ["NET_DEBT_BY_EBIT", "NET_DEBT_BY_EQUITY"],
    "efficiency": ["NET_MARGIN", "ROE"],
    "growth": ["CAGR_5_YEARS_PROFIT", "CAGR_5_YEARS_REVENUE"],
}

kpi_fundament_value_column = {
    "EQUITY": "VALUE_ROLLING_YEAR",
    "NET_REVENUE": "VALUE_ROLLING_YEAR",
    "PROFIT": "VALUE_ROLLING_YEAR",
    "EBIT": "VALUE_ROLLING_YEAR",
    "DEBT": "VALUE_ROLLING_YEAR",
    "DEBT_NET": "VALUE_ROLLING_YEAR",
    "NET_MARGIN": "VALUE",
    "ROE": "VALUE",
    "NET_DEBT_BY_EBIT": "VALUE_ROLLING_YEAR",
    "NET_DEBT_BY_EQUITY": "VALUE_ROLLING_YEAR",
    "CAGR_5_YEARS_PROFIT": "VALUE",
    "CAGR_5_YEARS_REVENUE": "VALUE",
}
